import { useEffect, useState } from 'react'

const email = 'cybercraftstudio@cybercraftstudio.net'
const mail = (subject) => `mailto:${email}?subject=${encodeURIComponent(subject)}`
const services = [
  ['Cybersecurity Consulting & Roadmapping','Help organizations understand their current security posture, identify gaps, prioritize improvements, define security requirements, and build a practical roadmap.','Consulting and Roadmapping Inquiry','Discuss consulting & roadmapping'],
  ['Security Assessments & VAPT','Assess exposed services, vulnerabilities, configurations, and security weaknesses, with practical findings and remediation priorities without generic automated report noise.','Security Assessments and VAPT Inquiry','Discuss security assessments'],
  ['Security Implementation','Implement and configure security controls, integrations, infrastructure, and tooling required to address identified security gaps and strengthen defensive posture.','Security Implementation Inquiry','Discuss implementation'],
  ['SIEM & Security Monitoring','Deploy and configure Wazuh-based monitoring, onboard core security data sources, develop custom detections, tune alerts, and improve security visibility.','SIEM and Security Monitoring Inquiry','Discuss SIEM & monitoring'],
]
const approach = [['Understand the environment','Review infrastructure, existing controls, business requirements, and current security gaps to establish an accurate baseline.'],['Prioritize what matters','Separate immediate risks from longer-term improvements and define a practical, realistic remediation roadmap.'],['Implement the right controls','Deploy, configure, or integrate the technologies and security controls needed to directly address those priorities.'],['Leave a useful handover',"Provide clear documentation, actionable findings, and systems the client's team can confidently operate and maintain."]]
const work = [
  ['bg-sand','Detection Engineering · Wazuh','From alert fatigue to an actionable queue.','Recurring Wazuh rules analyzed, false positives isolated, and detection logic engineered around real baseline behavior.','High-volume false positives masking real security events.','Actionable alert triage queue tailored to actual operational patterns.','Wazuh · Custom Decoders · Detection Logic','Detection Engineering Project Inquiry','Discuss detection engineering'],
  ['bg-ink text-white','Cloud Identity · M365 & Azure','Authentication activity, in one view.','Microsoft 365 and Azure AD events centralized to investigate failed and anomalous login patterns.','Dispersed SaaS authentication activity with limited audit visibility.','Centralized visibility to spot suspicious sign-ins and privilege changes.','Azure AD / Entra ID · M365 Defender · API Ingestion','Cloud Identity Monitoring Project Inquiry','Discuss cloud identity'],
  ['bg-mint','Network Visibility · Architecture Readiness','Architecture ready for deeper monitoring.','AWS sensor placement, traffic mirroring, and IPsec requirements coordinated for Vectra AI readiness.','Preparing cloud infrastructure for high-depth network sensors.','Validated network topologies and traffic feeds prior to sensor rollout.','AWS VPC Mirroring · IPsec VPN · Network Architecture','Network Visibility Project Inquiry','Discuss network architecture'],
]
const clients = [['Startups & SMEs','Early-stage and growing companies that need to establish a solid security foundation, address vulnerabilities, or prepare for customer vendor audits without enterprise complexity.'],['Growing IT Teams','Internal IT and systems teams needing specialized engineering to deploy SIEM, run vulnerability assessments, or harden cloud infrastructure alongside their daily operations.'],['MSPs & Tech Providers','Technology companies and service providers that require technical security consulting, custom detection tuning, or monitoring architecture for client environments.'],['Security Foundations','Organizations moving from ad-hoc security measures to structured, prioritized security roadmaps with practical, maintainable controls.']]
const Eyebrow=({children,light=false})=><p className={`font-mono text-[10px] font-medium uppercase tracking-[.11em] ${light?'text-[#dc927d]':'text-rust'}`}>{children}</p>
const Heading=({eyebrow,children})=><div className="mb-8 flex flex-col gap-3 sm:mb-10 sm:flex-row sm:items-baseline sm:gap-10"><Eyebrow>{eyebrow}</Eyebrow><h2 className="font-serif text-[clamp(2.55rem,4.1vw,3.65rem)] leading-[.98] tracking-[-.085em] [&_em]:text-rust">{children}</h2></div>

export default function App(){
  const [open,setOpen]=useState(false); const nav=[['Services','#services'],['Work','#work'],['Approach','#approach'],['Contact','#contact']]
  useEffect(() => {
    const sections = document.querySelectorAll('main > section, footer')
    sections.forEach((section) => section.classList.add('reveal'))
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add('is-visible')
          observer.unobserve(entry.target)
        }
      })
    }, { threshold: 0.12 })
    sections.forEach((section) => observer.observe(section))
    return () => observer.disconnect()
  }, [])
  return <><header className="sticky top-0 z-50 bg-paper/95 backdrop-blur"><div className="mx-auto flex h-[76px] w-[calc(100%-40px)] max-w-[1200px] items-center justify-between border-b border-line sm:h-[105px] sm:w-[calc(100%-72px)]"><a href="#top" className="font-serif text-[22px] tracking-[-.07em]">Uttam Jitendra<span className="text-rust">.</span></a><button aria-label="Toggle navigation" onClick={()=>setOpen(!open)} className="grid gap-1.5 p-2 sm:hidden"><span className="h-px w-6 bg-ink"/><span className="h-px w-6 bg-ink"/></button><nav className={`${open?'flex':'hidden'} absolute right-5 top-16 w-52 flex-col gap-5 bg-ink p-6 sm:static sm:flex sm:w-auto sm:flex-row sm:gap-8 sm:bg-transparent sm:p-0`}>{nav.map(([label,href])=><a onClick={()=>setOpen(false)} key={href} href={href} className="text-[10px] font-bold uppercase tracking-[.1em] text-white sm:text-ink sm:hover:text-rust">{label}</a>)}</nav></div></header>
  <main id="top"><section className="mx-auto grid w-[calc(100%-40px)] max-w-[1200px] gap-16 py-18 sm:w-[calc(100%-72px)] sm:grid-cols-[1.13fr_.87fr] sm:px-15 sm:py-30"><div><Eyebrow>Independent Cybersecurity Consultant</Eyebrow><h1 className="mt-5 max-w-[760px] font-serif text-[clamp(3.5rem,6.7vw,6.3rem)] leading-[.88] tracking-[-.095em]">Practical cybersecurity for <em className="text-rust">growing organizations.</em></h1><p className="mt-7 max-w-[530px] font-serif text-[17px] leading-[1.55] tracking-[-.02em] sm:text-[18px]">I help startups, SMEs, and growing teams understand their security gaps, prioritize what matters, and implement practical security controls - from security assessments and VAPT to SIEM, monitoring, and security integrations.</p><a href="#contact" className="mt-7 inline-flex items-center gap-3 bg-ink px-4 py-3.5 text-[13px] font-bold text-white hover:bg-rust">Discuss your security needs ↗</a><p className="mt-4 text-[11px] leading-5 text-copy">Consulting · Assessments & VAPT · Implementation · SIEM & Monitoring</p></div><aside className="self-end border-l border-[#bdae9c] pl-6 sm:pl-8"><p className="font-serif text-7xl leading-[.7] tracking-[-.12em] text-[#c6b69c] sm:text-[82px]">01</p><h2 className="mt-9 font-serif text-[28px] leading-none tracking-[-.06em]">One specialist.<br/>Direct execution.</h2><p className="mt-4 max-w-[260px] text-[13px] leading-6 text-copy">Fixed-scope consulting, assessments, and security engineering that work alongside your existing IT and engineering teams - without agency bloat or generic checklists.</p></aside></section>
  <div className="mx-auto h-px w-[calc(100%-40px)] max-w-[1200px] bg-line sm:w-[calc(100%-72px)]"/>
  <section id="start" className="border-b border-line py-15 sm:py-20"><div className="mx-auto w-[calc(100%-40px)] max-w-[1200px] sm:w-[calc(100%-72px)]"><Heading eyebrow="Guidance / Where to Begin">Not sure where to <em>start?</em></Heading><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:gap-25"><div><p className="max-w-[350px] font-serif text-[25px] leading-[1.18] tracking-[-.05em]">You don't need to know which security tools to buy before reaching out.</p><div className="mt-6 max-w-[400px] space-y-4 text-[13px] leading-6 text-copy"><p>Most growing companies don't need an expensive enterprise security suite. They need to know where their real exposures lie, which fixes deliver the highest defensive value, and what practical steps to take next.</p><p>I help evaluate your environment, identify critical gaps, and establish a prioritized path forward so you only invest in what your organization actually needs.</p><a href="#contact" className="inline-flex bg-ink px-4 py-3 text-[12px] font-bold text-white hover:bg-rust">Start with an exploratory review ↗</a></div></div><div className="grid border-t border-line sm:grid-cols-2">{[['01 / Assess','Assess your environment','Identify exposed services, vulnerable configurations, and key visibility blind spots across your infrastructure.'],['02 / Prioritize','Define priorities','Separate urgent risks from lower-priority items to build a focused, realistic security roadmap.'],['03 / Implement','Implement controls','Deploy tested security controls, integrations, and monitoring tailored to your actual operational stack.'],['04 / Improve','Improve continuously','Tune alert rules, review ongoing exposure, and ensure your internal team can confidently maintain security.']].map(([num,title,text])=><div key={num} className="border-b border-line py-5 sm:pr-5"><Eyebrow>{num}</Eyebrow><h3 className="mt-3 font-serif text-[23px] tracking-[-.05em]">{title}</h3><p className="mt-2 text-[12px] leading-5 text-copy">{text}</p></div>)}</div></div></div></section>
  <section id="services" className="mx-auto w-[calc(100%-40px)] max-w-[1200px] border-b border-line py-15 sm:w-[calc(100%-72px)] sm:py-20"><Heading eyebrow="01 / Services">Where I can help</Heading><div className="grid border-t border-line sm:grid-cols-2">{services.map(([title,body,subject,action],i)=><article key={title} className={`grid grid-cols-[42px_1fr] gap-3 border-b border-line py-7 ${i%2===0?'sm:border-r sm:pr-8':'sm:pl-8'}`}><span className="font-mono text-[12px] text-rust">0{i+1}</span><div><h3 className="font-serif text-[25px] leading-[1.03] tracking-[-.06em]">{title}</h3><p className="mt-3 text-[13px] leading-6 text-copy">{body}</p><a className="mt-4 inline-flex text-[11px] font-bold hover:text-rust" href={mail(subject)}>{action} <b className="ml-2 text-rust">↗</b></a></div></article>)}</div><p className="mt-9 max-w-[850px] border-l-[5px] border-rust pl-5 font-serif text-[27px] leading-[1.07] tracking-[-.06em] sm:text-[31px]">Not a 24/7 SOC or generic checklist auditor. Focused cybersecurity consulting, assessments, and engineering for organizations establishing or improving their security posture.</p></section>
  <section id="approach" className="bg-[#e9e1d2] py-15 sm:py-20"><div className="mx-auto w-[calc(100%-40px)] max-w-[1200px] sm:w-[calc(100%-72px)]"><Heading eyebrow="02 / The Approach">Built around your<br/><em>actual environment.</em></Heading><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:gap-25"><p className="max-w-[440px] font-serif text-[23px] leading-[1.3] tracking-[-.045em]">No generic security checklists. Each project is designed to address real risks, prioritize high-impact fixes, and make the systems you rely on easier to protect, investigate, and improve.</p><ol className="border-t border-[#c6b9a5]">{approach.map(([title,body],i)=><li key={title} className="grid grid-cols-[50px_1fr] gap-3 border-b border-[#c6b9a5] py-4"><span className="font-mono text-[11px] text-rust">0{i+1}</span><div><strong className="font-serif text-[22px] tracking-[-.045em]">{title}</strong><p className="mt-1.5 text-[12px] leading-5 text-copy">{body}</p></div></li>)}</ol></div></div></section>
  <section id="work" className="mx-auto w-[calc(100%-40px)] max-w-[1200px] border-b border-line py-15 sm:w-[calc(100%-72px)] sm:py-20"><Heading eyebrow="03 / Selected Work">Evidence of the approach</Heading><div className="grid gap-3 lg:grid-cols-3">{work.map(([tone,eyebrow,title,body,challenge,outcome,tags,subject,action])=><article key={title} className={`flex min-h-[330px] flex-col p-6 ${tone}`}><Eyebrow light={tone.includes('text-white')}>{eyebrow}</Eyebrow><h3 className="mt-12 font-serif text-[28px] leading-none tracking-[-.07em]">{title}</h3><p className={`mt-4 text-[13px] leading-6 ${tone.includes('text-white')?'text-[#d6d0c8]':'text-copy'}`}>{body}</p><div className={`mt-5 space-y-2 border-t pt-4 text-[11px] leading-5 ${tone.includes('text-white')?'border-white/25 text-[#d6d0c8]':'border-ink/15 text-copy'}`}><p><b>Challenge:</b> {challenge}</p><p><b>Outcome:</b> {outcome}</p><p className="font-mono text-[9px] uppercase tracking-wide">{tags}</p></div><a href={mail(subject)} className={`mt-auto pt-6 text-[11px] font-bold ${tone.includes('text-white')?'text-[#e6ddba]':'text-rust'}`}>{action} ↗</a></article>)}</div></section>
  <section id="who" className="mx-auto w-[calc(100%-40px)] max-w-[1200px] border-b border-line py-15 sm:w-[calc(100%-72px)] sm:py-20"><Heading eyebrow="04 / Client Profiles">Who I work <em>with.</em></Heading><div className="grid gap-px bg-line sm:grid-cols-2 lg:grid-cols-4">{clients.map(([title,body],i)=><article key={title} className="min-h-[235px] bg-paper p-5"><span className="font-mono text-[11px] text-rust">0{i+1}</span><h3 className="mt-10 font-serif text-[23px] leading-none tracking-[-.05em]">{title}</h3><p className="mt-3 text-[12px] leading-5 text-copy">{body}</p></article>)}</div></section>
  <section id="about" className="bg-[#e9e1d2] py-15 sm:py-20"><div className="mx-auto w-[calc(100%-40px)] max-w-[1200px] sm:w-[calc(100%-72px)]"><Heading eyebrow="05 / Profile & Credibility">Independent, practical, <em>hands-on.</em></Heading><div className="grid gap-10 lg:grid-cols-2 lg:gap-25"><div className="max-w-[520px] space-y-4 text-[13px] leading-6 text-copy"><p className="font-serif text-[23px] leading-[1.3] tracking-[-.045em] text-ink">Uttam Jitendra - Independent Cybersecurity Consultant based in Bengaluru, India.</p><p>I partner directly with founders, IT directors, and technical teams to identify vulnerabilities, build realistic security roadmaps, and implement effective security controls.</p><p>No generic automated report dumps, no account managers, and no enterprise theater. Every engagement is hands-on, clearly scoped, and designed to leave your team with systems and processes you can confidently operate.</p></div><div className="space-y-6 border-t border-[#c6b9a5] pt-5"><Meta title="Accreditation">Netskope Accredited</Meta><Meta title="Core Capabilities"><div className="flex flex-wrap gap-2">{['Cybersecurity Consulting','Security Assessments','Scoped VAPT','Security Roadmapping','Wazuh SIEM','Detection Engineering','Cloud & SaaS Monitoring','Security Integrations'].map(x=><span key={x} className="border border-[#bcae9d] px-2 py-1 font-mono text-[9px] uppercase tracking-wide">{x}</span>)}</div></Meta><Meta title="Engagement Model">Fixed-scope projects, scoped assessments, and direct advisory partnerships tailored to your environment.</Meta></div></div></div></section></main>
  <footer id="contact" className="bg-ink py-15 text-white sm:py-20"><div className="mx-auto w-[calc(100%-40px)] max-w-[1200px] sm:w-[calc(100%-72px)]"><div className="grid gap-12 lg:grid-cols-[1fr_.55fr]"><div><Eyebrow light>06 / Start A Conversation</Eyebrow><h2 className="mt-4 font-serif text-[clamp(2.8rem,4.5vw,4.2rem)] leading-[.92] tracking-[-.09em]">Tell me about your<br/>security <em className="text-[#dc927d]">priorities.</em></h2><p className="mt-6 max-w-[570px] text-[13px] leading-6 text-[#d6d0c8]">Whether you have a specific SIEM project, need a vulnerability assessment, or simply want to know where your security posture stands, let's discuss your environment.</p></div><div className="self-end text-[13px] leading-7"><a href={`mailto:${email}`} className="block hover:text-[#dc927d]">{email}</a><a href="tel:+919916259234" className="block hover:text-[#dc927d]">+91 99162 59234</a><p className="mt-5 text-[#b7b1a8]">Bengaluru, India<br/>Available for selected project-based consulting.</p></div></div><div className="mt-16 flex flex-col justify-between gap-3 border-t border-white/20 pt-5 font-mono text-[9px] uppercase tracking-wide text-[#b7b1a8] sm:flex-row"><span>Uttam Jitendra · Independent Cybersecurity Consultant</span><span>© {new Date().getFullYear()} All rights reserved.</span></div></div></footer></>
}
function Meta({title,children}){return <div><h4 className="font-mono text-[10px] uppercase tracking-[.1em] text-rust">{title}</h4><div className="mt-2 text-[13px] leading-6 text-copy">{children}</div></div>}
